import { readFile, writeFile } from 'node:fs/promises';
import { URL as NodeURL } from 'node:url';
import {
  complexities,
  difficulties,
  formats,
  nearDuplicates,
  normalizedQuestion,
  type Question,
} from '../src/features/grounding/schema';
import { isMain, loadContent } from './validate-questions';

function countBy(questions: Question[], key: keyof Question) {
  return questions.reduce<Record<string, number>>((counts, question) => {
    const value = String(question[key]);
    counts[value] = (counts[value] ?? 0) + 1;
    return counts;
  }, {});
}

export async function buildReport() {
  const { questions, manifest, taxonomy } = await loadContent();
  const maintenance = await readFile(
    new NodeURL('../docs/content-maintenance.md', import.meta.url),
    'utf8',
  );
  const counts = {
    domain: countBy(questions, 'objectiveDomain'),
    skill: countBy(questions, 'skill'),
    subskill: countBy(questions, 'subskill'),
    difficulty: countBy(questions, 'difficulty'),
    complexity: countBy(questions, 'complexity'),
    format: countBy(questions, 'questionType'),
  };
  const missingCitations = questions
    .filter(
      (q) =>
        !q.sourceIds.length ||
        !q.sourceUrls.length ||
        !q.documentationTitles.length,
    )
    .map((q) => q.id);
  const texts = questions.map((q) => normalizedQuestion(q.question));
  const duplicates = questions
    .filter((_, index) => texts.indexOf(texts[index]) !== index)
    .map((q) => q.id);
  const uncoveredSubskills = taxonomy.domains.flatMap((domain) =>
    domain.skills.flatMap((skill) =>
      skill.subskills
        .filter(
          (subskill) =>
            !questions.some(
              (q) =>
                q.objectiveDomain === domain.id &&
                q.skill === skill.id &&
                q.subskill === subskill,
            ),
        )
        .map((subskill) => ({
          domain: domain.title,
          skill: skill.title,
          subskill,
        })),
    ),
  );
  const uncovered = {
    domains: taxonomy.domains
      .filter((d) => !counts.domain[d.id])
      .map((d) => d.title),
    skills: taxonomy.domains.flatMap((d) =>
      d.skills.filter((s) => !counts.skill[s.id]).map((s) => s.title),
    ),
    difficulties: difficulties.filter((value) => !counts.difficulty[value]),
    complexities: complexities.filter((value) => !counts.complexity[value]),
    formats: formats.filter((value) => !counts.format[value]),
  };
  const dates = questions.map((q) => q.lastValidatedAt).sort();
  const table = (heading: string, values: Record<string, number>) => [
    `## ${heading}`,
    '',
    '| Category | Questions |',
    '| --- | ---: |',
    ...Object.entries(values).map(
      ([label, count]) => `| ${label} | ${count} |`,
    ),
    '',
  ];
  const totalSubskills = taxonomy.domains.reduce(
    (sum, domain) =>
      sum + domain.skills.reduce((n, skill) => n + skill.subskills.length, 0),
    0,
  );
  const lines = [
    '# Content coverage',
    '',
    'Generated by `npm run content:report -- --write`. Counts describe this local practice bank, not predicted exam frequency or exam readiness.',
    '',
    `- Questions: **${questions.length}**, authored as original scenarios and code exercises.`,
    `- Taxonomy: **${taxonomy.domains.length} domains**, **${taxonomy.domains.flatMap((d) => d.skills).length} skills**, **${totalSubskills} subskills**.`,
    `- Subskills sampled: **${totalSubskills - uncoveredSubskills.length}/${totalSubskills}**. One primary subskill is assigned per question.`,
    `- Study guide effective date: **${taxonomy.studyGuideEffectiveDate}**.`,
    `- Taxonomy retrieved: ${taxonomy.retrievedAt}.`,
    `- Last grounded through Microsoft Learn MCP: ${manifest.lastGroundedAt}.`,
    `- Question validation dates: oldest ${dates[0]}; newest ${dates.at(-1)}.`,
    `- ${maintenance.match(/^Last successful online URL validation:.*$/m)?.[0] ?? 'Online URL validation: not recorded.'}`,
    `- Source records: ${manifest.sources.length}; unique URLs: ${new Set(manifest.sources.map((s) => s.url)).size}.`,
    `- Missing citations: ${missingCitations.length}; exact duplicate questions: ${duplicates.length}; near-duplicate pairs: ${nearDuplicates(questions).length}.`,
    `- Feature labels: GA ${questions.filter((q) => q.featureStatus === 'GA').length}; Preview ${questions.filter((q) => q.featureStatus === 'Preview').length}.`,
    '',
    ...table(
      'Objective domains',
      Object.fromEntries(
        taxonomy.domains.map((d) => [
          `${d.title} (${d.weightRange.join('–')}% guide weight)`,
          counts.domain[d.id] ?? 0,
        ]),
      ),
    ),
    ...table(
      'Skills',
      Object.fromEntries(
        taxonomy.domains.flatMap((d) =>
          d.skills.map((s) => [s.title, counts.skill[s.id] ?? 0]),
        ),
      ),
    ),
    ...table(
      'Difficulty',
      Object.fromEntries(
        difficulties.map((v) => [v, counts.difficulty[v] ?? 0]),
      ),
    ),
    ...table(
      'Complexity',
      Object.fromEntries(
        complexities.map((v) => [v, counts.complexity[v] ?? 0]),
      ),
    ),
    ...table(
      'Question format',
      Object.fromEntries(formats.map((v) => [v, counts.format[v] ?? 0])),
    ),
    ...table(
      'Subskill counts (including gaps)',
      Object.fromEntries(
        taxonomy.domains.flatMap((d) =>
          d.skills.flatMap((s) =>
            s.subskills.map((v) => [v, counts.subskill[v] ?? 0]),
          ),
        ),
      ),
    ),
    '## Uncovered categories',
    '',
    ...Object.entries(uncovered).map(
      ([category, values]) =>
        `- ${category}: ${values.length ? values.join('; ') : 'None'}.`,
    ),
    '',
    '## Uncovered subskills',
    '',
    ...uncoveredSubskills.map((gap) => `- **${gap.skill}** — ${gap.subskill}`),
    '',
    '## Grounding and limitations',
    '',
    '- The study guide is the taxonomy authority. The certification and instructor-led course pages were fetched, but their dynamic skills sections returned “Loading” placeholders. They are context sources, not evidence for implementation answers.',
    '- Self-paced management learning path, CI/CD module, monitoring module, and monitoring/Activator learning units were separately retrieved. No linked assessment or knowledge-check page was opened.',
    '- Each question cites detailed implementation documentation or a relevant learning unit. Source summaries are original paraphrases; full MCP responses remain ignored in `.grounding`.',
    '- Difficulty is an editorial learning aid, not an official Microsoft rating. Balanced counts do not imply equal depth or full subskill coverage.',
    '- GA labels describe the specific behavior tested, not every feature mentioned on a source page. Experimental/new-runtime Spark APIs and the preview Lakehouse Maintenance pipeline activity are not tested.',
    '- The PySpark API reference is hosted under Azure Databricks; its standard DataFrame operations are paired with Fabric Python support documentation. Databricks-specific catalog and workspace behavior is not inferred for Fabric.',
    '- Code snippets are original illustrative exercises, not live-tested against a Fabric tenant. The app never executes them.',
    '- The report requires structural validation first and fails closed on invalid content. URL reachability checks cannot establish that an answer is factually correct; human claim review and MCP retrieval remain required.',
    '',
  ];
  return lines.join('\n');
}

if (isMain(import.meta.url)) {
  try {
    const report = await buildReport();
    if (process.argv.includes('--write')) {
      await writeFile(
        new NodeURL('../docs/content-coverage.md', import.meta.url),
        report,
      );
      console.log('Wrote docs/content-coverage.md');
    } else {
      console.log(report);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
